### ISSUE TITLE
asdasdasd

### ISSUE THREAD

**Issue by fzdwx** [atomicoke/go-zero#17]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, if applicable:

1. The code is

   ```go
   
   ```

2. The error is

   ```
   
   ```

**Expected behavior**

**Screenshots**

**Environments (please complete the following information):**
 - OS: [e.g. Linux]
 - go-zero version [e.g. 1.2.1]
 - goctl version [e.g. 1.2.1, optional]

**More description**

**Comment by cehnhy** [comment]
qwe

**Comment by fzdwx** [comment]
asdasdasd

**Comment by cehnhy** [comment]
asd

**Comment by cehnhy** [comment]
qwe

**Comment by cehnhy** [comment]
qwe
